name: MarshmallowCastle
favicon: null
layout_spectrum: 0.579537422163412
typography_spectrum: 0.925556251546368
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.8686367580667138
  lightness: 0.5061514908447862
  saturation: 0.11071675014682114
  rhythmicContrast: 0.10560382436960936
purpose: []
