name: MarshmallowCastle
favicon: null
layout_spectrum: 0.1939
typography_spectrum: 0.925556251546368
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfdfd'
    - '#040500'
    - '#c2b09c'
    - '#574f44'
    - '#8f1009'
  brandStrength: 0.875
  lightness: 0.5061514908447862
  saturation: 0.1875
  rhythmicContrast: 0.25
purpose: []
